"""empty message

Revision ID: 0425ad55bbb3
Revises: 6d7ca9d9a6b1
Create Date: 2019-12-10 01:54:35.542871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0425ad55bbb3'
down_revision = '6d7ca9d9a6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('student', 'sid',
    #           existing_type=sa.VARCHAR(),
    #           type_=sa.Integer(),
    #           autoincrement=True)
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'sid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               autoincrement=True)
    # ### end Alembic commands ###
