"""empty message

Revision ID: 2707ef6ae4c1
Revises: baf0ad510fda
Create Date: 2019-12-10 02:17:09.127453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2707ef6ae4c1'
down_revision = 'baf0ad510fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'sid',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'sid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               autoincrement=True)
    # ### end Alembic commands ###
