"""empty message

Revision ID: 2c05e2466437
Revises: b05d7d73ea69
Create Date: 2019-12-10 17:07:06.374839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c05e2466437'
down_revision = 'b05d7d73ea69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('student_sid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'student', ['student_sid'], ['sid'])
    op.add_column('passport', sa.Column('student_sid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'passport', 'student', ['student_sid'], ['sid'])
    op.add_column('visa', sa.Column('student_sid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visa', 'student', ['student_sid'], ['sid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visa', type_='foreignkey')
    op.drop_column('visa', 'student_sid')
    op.drop_constraint(None, 'passport', type_='foreignkey')
    op.drop_column('passport', 'student_sid')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'student_sid')
    # ### end Alembic commands ###
