"""empty message

Revision ID: 39eedd4e46d2
Revises: d277507579e9
Create Date: 2019-12-09 03:03:10.150223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39eedd4e46d2'
down_revision = 'd277507579e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Visa',
    sa.Column('visa_num', sa.Integer(), nullable=False),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('date_of_expiration', sa.Date(), nullable=True),
    sa.Column('visa_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('visa_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Visa')
    # ### end Alembic commands ###
