"""empty message

Revision ID: 5961dc056db9
Revises: 14893256b401
Create Date: 2019-12-10 23:22:09.074036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5961dc056db9'
down_revision = '14893256b401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('has_major',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('cid_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cid_code'], ['major.cip_code'], ),
    sa.ForeignKeyConstraint(['sid'], ['student.sid'], ),
    sa.PrimaryKeyConstraint('sid', 'cid_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('has_major')
    # ### end Alembic commands ###
