"""empty message

Revision ID: 597a5dfb7ac0
Revises: 763d6f449178
Create Date: 2019-12-07 10:44:09.816048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597a5dfb7ac0'
down_revision = '763d6f449178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major', sa.Column('abbreviation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('major', 'abbreviation')
    # ### end Alembic commands ###
