"""empty message

Revision ID: 6848d251d9b3
Revises: a64c11db69a0
Create Date: 2019-12-10 01:05:43.145935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6848d251d9b3'
down_revision = 'a64c11db69a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('student_sid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'passport', 'student', ['student_sid'], ['sid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passport', type_='foreignkey')
    op.drop_column('passport', 'student_sid')
    # ### end Alembic commands ###
