"""empty message

Revision ID: 6d7ca9d9a6b1
Revises: 925341bc6d28
Create Date: 2019-12-10 01:51:08.433903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7ca9d9a6b1'
down_revision = '925341bc6d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'sid',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'sid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               autoincrement=True)
    # ### end Alembic commands ###
