"""empty message

Revision ID: 763d6f449178
Revises: 71e9422332bf
Create Date: 2019-12-02 22:33:43.215692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763d6f449178'
down_revision = '71e9422332bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('cip_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cip_code')
    )
    op.create_table('passport',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('date_of_expiration', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('student',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('preferred_name', sa.String(), nullable=True),
    sa.Column('legal_first', sa.String(), nullable=True),
    sa.Column('legal_middle', sa.String(), nullable=True),
    sa.Column('legal_last', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('class_year', sa.Integer(), nullable=True),
    sa.Column('ac_box', sa.String(), nullable=True),
    sa.Column('ac_email', sa.String(), nullable=True),
    sa.Column('sevis_id', sa.String(), nullable=True),
    sa.Column('sevis_status', sa.String(), nullable=True),
    sa.Column('program_start_date', sa.Date(), nullable=True),
    sa.Column('program_end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.add_column('example', sa.Column('eid', sa.Integer(), nullable=False))
    op.drop_column('example', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('example', 'eid')
    op.drop_table('student')
    op.drop_table('passport')
    op.drop_table('major')
    # ### end Alembic commands ###
