"""empty message

Revision ID: 925341bc6d28
Revises: 6848d251d9b3
Create Date: 2019-12-10 01:49:47.957965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925341bc6d28'
down_revision = '6848d251d9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('student_sid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'passport', 'student', ['student_sid'], ['sid'])
    op.alter_column('student', 'sid',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'sid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               autoincrement=True)
    op.drop_constraint(None, 'passport', type_='foreignkey')
    op.drop_column('passport', 'student_sid')
    # ### end Alembic commands ###
