"""empty message

Revision ID: a64c11db69a0
Revises: fbdbb12d55a1
Create Date: 2019-12-10 01:02:14.786628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64c11db69a0'
down_revision = 'fbdbb12d55a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('visa',
    sa.Column('visa_num', sa.Integer(), nullable=False),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('date_of_expiration', sa.Date(), nullable=True),
    sa.Column('visa_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('visa_num')
    )
    op.drop_table('Note')
    op.drop_table('Staff')
    op.drop_table('Visa')
    op.drop_constraint('passport_student_sid_fkey', 'passport', type_='foreignkey')
    op.drop_column('passport', 'student_sid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('student_sid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('passport_student_sid_fkey', 'passport', 'student', ['student_sid'], ['sid'])
    op.create_table('Visa',
    sa.Column('visa_num', sa.INTEGER(), server_default=sa.text('nextval(\'"Visa_visa_num_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('date_of_issue', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_of_expiration', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('visa_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('visa_num', name='Visa_pkey')
    )
    op.create_table('Staff',
    sa.Column('staff_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Staff_staff_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('staff_id', name='Staff_pkey')
    )
    op.create_table('Note',
    sa.Column('note_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Note_note_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('note_id', name='Note_pkey')
    )
    op.drop_table('visa')
    op.drop_table('staff')
    op.drop_table('note')
    # ### end Alembic commands ###
