"""empty message

Revision ID: b05d7d73ea69
Revises: 4eb459d7f788
Create Date: 2019-12-10 16:53:32.217661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05d7d73ea69'
down_revision = '4eb459d7f788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('cip_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cip_code')
    )
    op.create_table('note',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('passport',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('date_of_expiration', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('student',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('preferred_name', sa.String(), nullable=True),
    sa.Column('legal_first', sa.String(), nullable=True),
    sa.Column('legal_middle', sa.String(), nullable=True),
    sa.Column('legal_last', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('class_year', sa.Integer(), nullable=True),
    sa.Column('ac_box', sa.String(), nullable=True),
    sa.Column('ac_email', sa.String(), nullable=True),
    sa.Column('sevis_id', sa.String(), nullable=True),
    sa.Column('sevis_status', sa.String(), nullable=True),
    sa.Column('program_start_date', sa.Date(), nullable=True),
    sa.Column('program_end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('visa',
    sa.Column('visa_num', sa.Integer(), nullable=False),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('date_of_expiration', sa.Date(), nullable=True),
    sa.Column('visa_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('visa_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visa')
    op.drop_table('student')
    op.drop_table('staff')
    op.drop_table('passport')
    op.drop_table('note')
    op.drop_table('major')
    # ### end Alembic commands ###
