"""empty message

Revision ID: d00776819f4a
Revises: 658fe477ca55
Create Date: 2019-11-28 01:45:00.122160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00776819f4a'
down_revision = '658fe477ca55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testt')
    # ### end Alembic commands ###
