"""empty message

Revision ID: d277507579e9
Revises: 597a5dfb7ac0
Create Date: 2019-12-07 11:18:48.432498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd277507579e9'
down_revision = '597a5dfb7ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('student_sid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'passport', 'student', ['student_sid'], ['sid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passport', type_='foreignkey')
    op.drop_column('passport', 'student_sid')
    # ### end Alembic commands ###
