"""empty message

Revision ID: d9cdd9177acd
Revises: 14d0505f2480
Create Date: 2019-12-10 02:32:24.768475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cdd9177acd'
down_revision = '14d0505f2480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('student_sid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'passport', 'student', ['student_sid'], ['sid'])
    # ### end Alembic commands ###
    op.drop_table('passport')
    op.drop_table('')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passport', type_='foreignkey')
    op.drop_column('passport', 'student_sid')
    # ### end Alembic commands ###
