"""empty message

Revision ID: ab8aa68f4bfa
Revises: 
Create Date: 2019-11-03 21:41:11.508568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8aa68f4bfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('majors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majors',
    sa.Column('cip_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('foo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cip_code', name='majors_pkey')
    )
    op.drop_table('books')
    # ### end Alembic commands ###
